export const quotes: string[] = [
  "The difference between the impossible and the possible lies in a man's determination.",
  "Don't measure yourself by what you have accomplished, but by what you should have accomplished with your ability.",
  'Excellence is not a singular act but a habit. You are what you do repeatedly.',
  "A champion is someone who gets up when he can't.",
  'One man practicing sportsmanship is far better than 50 preaching it.',
  `It's not the will to win that matters. Everyone has that. It's the will to prepare to win that matters.`,
  'Do you know what my favorite part of the game is? The opportunity to play.',
  'The time when there is no one there to feel sorry for you or to cheer for you is when a player is made.',
  "Sportsmanship for me is when a guy walks off the court and you really can't tell whether he won or lost, when he carries himself with pride either way.",
  "You miss 100 percent of the shots you don't take.",
  'Statistics are like bikinis. They show a lot but not everything.',
  'I learned that if you want to make it bad enough, no matter how bad it is, you can make it.',
  "Set your goals high, and don't stop till you get there.",
  'It took me seventeen years to get three thousand hits in baseball. I did it in one afternoon on the golf course.',
  'When you lose a couple of times, it makes you realize how difficult it is to win.',
  "Close don't count in baseball. Close only counts in horseshoes and grenades.",
  "Age is no barrier. It's a limitation you put on your mind.",
  'Chemistry is a class you take in high school or college, where you figure out two plus two is 10, or something.',
  'Nobody in football should be called a genius. A genius is a guy like Norman Einstein.',
  'I spent 90 percent of my money on women and drink. The rest I wasted!',
  "I quit school in the sixth grade because of pneumonia. Not because I had it, but because I couldn't spell it.",
  "We can't win at home. We can't win on the road. As general manager, I just can't figure out where else to play.",
  "I feel like I'm the best, but you're not going to get me to say that.",
  'I figure practice puts your brains in your muscles.',
  'The fewer rules a coach has, the fewer rules there are for players to break.',
  'The difference between the old ballplayer and the new ballplayer is the jersey. The old ballplayer cared about the name on the front. The new ballplayer cares about the name on the back.',
  `It's not the will to win that matters-everyone has that. It's the will to prepare to win that matters.`,
  'The time when there is no one there to feel sorry for you or to cheer for you is when a player is made.',
  "Sportsmanship for me is when a guy walks off the court and you really can't tell whether he won or lost, when he carries himself with pride either way.",
  'The difference between the old ballplayer and the new ballplayer is the jersey. The old ballplayer cared about the name on the front. The new ballplayer cares about the name on the back.',
];